version: 0.1

phases:
  # pre_build:
  #   commands:
  #     - if [ "$IS_CI" = "true" ]; then echo $CODEBUILD_SOURCE_VERSION > git_commit_id; else chmod +x ./version_stamp.sh && ./version_stamp.sh; fi
  #     - npm install
  build:
    commands:
      - echo 'Making data files'
      - echo ${sshkey} > ~/.ssh/sshkey.pem
      - chmod 400 ~/.ssh/sshkey.pem
      - ssh -i  ~/.ssh/sshkey.pem ec2-user@ec2-3-83-230-91.compute-1.amazonaws.com 'uptime'